### ISSUE TITLE
 Render implements echo.Render interface

### ISSUE THREAD

**Issue by xuanjiang1985** [mayowa/echo-pongo2#1]
//example below
func (r *Renderer) Render(w io.Writer, name string, data interface{}, c echo.Context) error {
  ...
}

**Comment by mayowa** [comment]
If memory serves this is the new Render interface that came with echo 3. 
I didn't realize that there was anybody was using this library. I'll update it in about an hour or so.

**Comment by mayowa** [comment]
Done, please let me know if you find any other issue.
